Create a Simple Rail Network Simulation 2 Versuch
Gluecksritter/hello_world pull request #38
Opened 2017-11-01 12:59 UTC by Gluecksritter

Neue Auflage #35

2017-11-01 14:17 UTC, nipafx requested changes

2017-11-01 14:17 UTC, nicolaiparlog commented on src/main/kotlin/trainSimulation/Main.kt
> +import traffic_simulation.FileAccess
Dieser Import hier ist falsch.

2017-11-01 14:17 UTC, nicolaiparlog commented on src/main/kotlin/trainSimulation/Main.kt
> +        var trainListCSV: List<Train> = parseInputOfCSV(fileName = "driveInterest.csv")
Die Methode `parseInputOfCSV` ist nirgends definiert.

2017-11-01 14:17 UTC, nicolaiparlog commented on src/main/kotlin/trainSimulation/Main.kt
> +    fun main(args: Array<String>){
Die `main` Methode muss außerhalb einer Klasse definiert werden. (Damit meine ich nicht "außerhalb einer Datei" sondern außerhalb eines `class ... { ... }`-Blocks. Das Problem lässt sich hier am einfachsten beheben indem man den ganzen `class` Block entfernt und nur die Funktionen übrig lässt.

2017-11-01 14:17 UTC, nicolaiparlog commented on src/main/kotlin/trainSimulation/Main.kt
> +    fun delayFunction(listTrains: List<Train>, listSegments: List<RailSegment>): List<RailSegment>{
Diese Funktion und `applyDelay` gehört ins `RailNetwork`.

2017-11-01 14:29 UTC, Gluecksritter commented on src/main/kotlin/trainSimulation/Main.kt
> +import traffic_simulation.FileAccess
hier flasch, heißt der import muss wo anders hin oder kann komplett raus?

2017-11-01 14:51 UTC, Gluecksritter commented on src/main/kotlin/trainSimulation/Main.kt
> +import traffic_simulation.FileAccess
Zeile 8 ist entfernt

2017-11-01 14:51 UTC, Gluecksritter commented on src/main/kotlin/trainSimulation/Main.kt
> +    fun main(args: Array<String>){
erledigt

2017-11-01 14:55 UTC, Gluecksritter commented on src/main/kotlin/trainSimulation/Main.kt
> +    fun delayFunction(listTrains: List<Train>, listSegments: List<RailSegment>): List<RailSegment>{
ok

2017-11-01 15:25 UTC, Gluecksritter commented on src/main/kotlin/trainSimulation/Main.kt
> +        var trainListCSV: List<Train> = parseInputOfCSV(fileName = "driveInterest.csv")
Habe ich das so richtig verstanden?

2017-11-01 18:08 UTC, nicolaiparlog commented on src/main/kotlin/trainSimulation/Main.kt
> +        var trainListCSV: List<Train> = parseInputOfCSV(fileName = "driveInterest.csv")
Jetzt ist zumindest der Compiler zufrieden. Nur macht die Methode jetzt noch nichts. :wink:

2017-11-01 18:09 UTC, nicolaiparlog commented on src/main/kotlin/trainSimulation/Main.kt
> +import traffic_simulation.FileAccess
Ohne die Zeile geht es aber auch nicht. Sowohl IntelliJ als auch Maven (wahlweise von dir ausgeführt oder von Travis) weisen dich darauf hin. Das müsstest du selber lösen können.

2017-11-01 21:47 UTC, Gluecksritter commented on src/main/kotlin/trainSimulation/Main.kt
> +        var trainListCSV: List<Train> = parseInputOfCSV(fileName = "driveInterest.csv")
Methode ist betriebsbereit.

2017-11-02 09:02 UTC, Gluecksritter commented
@nicolaiparlog wieso beschwert sich travis denn hier noch genau?

2017-11-02 09:38 UTC, nicolaiparlog commented
Du musst nicht auf Travis warten, um sowas zu sehen. Du solltest vor jedem Commit lokal mit Maven bauen, um sicherzustellen, das alles funktioniert. In diesem Fall sagt Maven:

```
[ERROR] src/main/kotlin/trainSimulation/Main.kt:[56,36] Unresolved reference: delayFunction
[ERROR] src/main/kotlin/trainSimulation/Main.kt:[58,47] Unresolved reference: applyDelay
[ERROR] src/main/kotlin/trainSimulation/Main.kt:[101,36] Unresolved reference: delayFunction
[ERROR] src/main/kotlin/trainSimulation/Main.kt:[103,24] Unresolved reference: applyDelay
```

Das ist eigentlich ziemlich eindeutig: In `Main` konnten die Referenzen auf `delayFunction` und `applyFunction` nicht aufgelöst werden. Wenn du dir das in IntelliJ anguckst, siehst du auch, dass die beide rot markiert sind.

Du hast die Methoden zwar verschoben aber vergessen die Aufrufe entsprechend zu korrigieren. Die Methoden müssen jetzt auf `railNetwork` aufgerufen werden.

2017-11-02 11:24 UTC, nipafx approved these changes

2017-11-02 11:26 UTC, merged

2017-11-02 11:38 UTC, nicolaiparlog commented on src/main/kotlin/trainSimulation/Main.kt
> +        var trainListCSV: List<Train> = parseInputOfCSV(fileName = "../../resources/TrainSchedule.csv")
Der Pfad funktioniert so nicht. Die Klasse wird nicht an genau der Stelle ausgeführt, an der der Code liegt und aufgrund der verwendeten Methode `getResourceAsStream` wird bereits im `resources` Ordner nachgeguckt. D.h. hier reicht `"TrainSchedule.csv"`.

2017-11-02 11:39 UTC, nicolaiparlog commented
Das müsstest du bei dir aber eigentlich gemerkt haben...

2017-11-02 12:00 UTC, Gluecksritter commented
ich hab leider aktuell kleine Porbleme mit Intellij, auch delay und apply wurden nicht rot unterlegt. Daher ging das jetzt etwas zäh voran.